/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityManagementTable: typeof import('./../components/activities/ActivityManagementTable.vue')['default']
    ActivityReviewDrawer: typeof import('./../components/reviews/ActivityReviewDrawer.vue')['default']
    ActivityReviewTable: typeof import('./../components/reviews/ActivityReviewTable.vue')['default']
    AdminLayout: typeof import('./../components/layout/AdminLayout.vue')['default']
    AsyncState: typeof import('./../components/common/AsyncState.vue')['default']
    AuditLogTable: typeof import('./../components/governance/AuditLogTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileReviewList: typeof import('./../components/reviews/FileReviewList.vue')['default']
    IdentityReviewList: typeof import('./../components/reviews/IdentityReviewList.vue')['default']
    PageHeader: typeof import('./../components/common/PageHeader.vue')['default']
    ReportReviewList: typeof import('./../components/reviews/ReportReviewList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./../components/common/StatusTag.vue')['default']
  }
}
